# 4. Linear algebra operations

In [1]:
import numpy as np

## Linear Algebra

- A branch of mathematics dealing with vector spaces. 
- Basic operations: 
  - transpose, 
  - dot products, 
  - matrix multiplication
  
  

## LA and data science 
- Useful for manipulating numeric datasets. 
- Avoid writing explicit loops, making code:
  - more readable (closes to mathematical formulation)
  - more concise
  - faster to execute.

## Linear regression with LA

- Iimplement linear regression using `numpy` linear algebra operations. 
- Start with the functional form of the regression: 
   - how the predicted target values depend on the regression coefficients the of features (aka predictors or regressors). 

## Linear regression formula

Given: 

- coefficients $\mathrm{\beta}$ 
- matrix with the predictors $\mathrm{X}$ 

We can calculate predicted targets $\mathrm{\hat{y}}$ according to:
$$
\mathrm{\hat{y}} = \beta_0 + \mathrm{X}\mathrm{\beta}
$$

## Constant feature

Add an extra column of $1$s to the matrix $\mathrm{X}$.  
We can now omit intercept $\beta_0$ and get equivalent predictions, as $\beta_0$ is absorbed into vector of coefficients $\beta$

$$
\mathrm{\hat{y}} = \mathrm{X}\mathrm{\beta}
$$

## Matrix multiplication

- The  operation $X\beta$ is **matrix multiplication**. 
- Here, first matrix is $N\times M$ where N is the number datapoints (rows) and $M$ the number of predictors (including the extra row of ones). 
- The second matrix is $M\times 1$, so it is a column vector.

## Multiplying a matrix by a column vector

- For each row of X, we multiply it with $\beta$ elementwise and the  sum the resulting vector values is our predicted $\hat{y}$ for each row. This can be written explicitly as:

$$
\mathrm{\hat{y}_i} = \sum_{m=1}^M X_{i,m} \beta_m
$$

- The matrix multiplication version is much more concise. 
- The same is true in numpy code: it's more concise to implement this using the matrix multiplication function `numpy.dot` than write a bunch of loops.

## Matrix multiplication / dot product

- In `numpy` the concept of dot product (aka scalar product) is treated as
a special case of matrix multiplication. 
- The function `numpy.dot` works for: 
  - simple dot product between vectors, 
  - multiplying a matrix by a vector, 
  - multiplying two matrices.

## Dot product

- The definition of dot product between two vectors $u$ and $v$ is:

$$\langle u, v\rangle = \sum_{i=1}^N u_i v_i$$

- Other notations that you will come across for this operation are:
  - $u \cdot v$, 
  - $u^T v$.


In `numpy` we write

```python
np.dot(u, v)
```
or equivalent:

```python
u.dot(v)
```

### Exercise 4.1

Create two vectors of random values between -10 and 10 of size 100. Compute:
- elementwise product between them
- dot (scalar) product between them.


In [2]:
np.random.seed(666)

# 8<------------------------------
u = np.random.uniform(-10, 10, 100)
v = np.random.uniform(-10, 10, 100)


In [3]:
print((u * v).sum())
print()
print(u.dot(v))

-252.017874219

-252.017874219


In [4]:
# In newer versions of Python we can use the operator symbol `@` for the method `dot`:
print(u @ v)

-252.017874219


## Matrix multiplication in the general case

- Number of columns in the first one needs to be equal to the number of rows in the second one. 
- For matrices $A_{m\times n}$ and $B_{n \times p}$, the resulting matrix will be $C_{m \times p}$. 

## Matrix multiplication: definition

$$
C_{i,j} = \sum_{k=1}^n A_{i,k}B_{k,j}
$$
![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/470px-Matrix_multiplication_diagram_2.svg.png)

In `numpy` we simply use `dot`:

```python
np.dot(A, B)
```
or

```python
A.dot(B)
```

or we can use the symbol `@` which makes our code even more concise and readable:

```python
A @ B
```

### Exercise 4.2

- Create a random matrix $A_{3\times 4}$ and another random matrix $B_{4 \times 2}$. Multiply AB.  

In [5]:
# 8<---------------------------------
A = np.random.normal(0, 1, (3, 4))
B = np.random.normal(0, 1, (4, 2))
print(A.dot(B))
print(A @ B)

[[ 1.57637151 -1.64474143]
 [-0.68646281  0.82852164]
 [ 6.59310042 -2.45441846]]
[[ 1.57637151 -1.64474143]
 [-0.68646281  0.82852164]
 [ 6.59310042 -2.45441846]]


- Create a random matrix $C_{3\times 3}$ and $D_{3\times3}$. Multiply CD. Multiply DC. Is matrix multiplication [commutative](https://en.wikipedia.org/wiki/Commutative_property)?

In [6]:
# 8<------------------------------------
C = np.random.normal(0, 1, (3, 3))
D = np.random.normal(0, 1, (3, 3))
print(C @ D)
print(D @ C)

[[-1.95011228 -1.81030485 -0.45069052]
 [-0.26567549 -0.68307508 -0.64852351]
 [-1.23565255  0.28517766  2.00907736]]
[[-1.07179132  1.89857574 -1.27585634]
 [-0.41095456  2.12010645 -0.60202606]
 [-1.37317152  0.30924139 -1.67242512]]


- Create a identity matrix $I_{3\times 3}$.  Multiply IC, CI, DI, ID. What do you notice?

In [7]:
# 8<------------------------
I = np.eye(3)
print(I)
print(C)
print(I @ C)
print(C @ I)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.78590233 -0.37198983  1.01149733]
 [ 0.28176446 -0.48816932  0.2558341 ]
 [ 0.07928801  1.31558859  0.077067  ]]
[[ 0.78590233 -0.37198983  1.01149733]
 [ 0.28176446 -0.48816932  0.2558341 ]
 [ 0.07928801  1.31558859  0.077067  ]]
[[ 0.78590233 -0.37198983  1.01149733]
 [ 0.28176446 -0.48816932  0.2558341 ]
 [ 0.07928801  1.31558859  0.077067  ]]


- What will be the result of multiplying a matrix $Z_{m\times n}$ by a matrix $O_{n \times p}$ whose all entries are zero? Check your answer using some examples in `numpy`.

In [8]:
# 8<---------------------
O = np.zeros((4, 3))
print(O)
print(A @ O)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


### Exercise 4.3

- Create a random matrix $A_{3\times 4}$ and another random matrix $B_{2 \times 4}$. Can you transform one of them so that they can be multiplied? Try this in `numpy`.

In [9]:
# 8<----------------------------------
A = np.random.uniform(-1,1,(3,4))
B = np.random.uniform(-2,2,(2,4))
print(A.dot(B.T))
print(A @ B.T)

[[-0.63382655 -0.72932328]
 [-1.10639798  2.54024855]
 [-0.03414218 -0.41075148]]
[[-0.63382655 -0.72932328]
 [-1.10639798  2.54024855]
 [-0.03414218 -0.41075148]]


## Transpose

We have already encountered matrix transpose. 

- Math notation for transpose of matrix $A$ is $A^T$. 
- Transposing a matrix means making the rows into columns and columns into rows. 
- If $A$ is $m \times n$ then $A^T$ is $n \times m$. 
- The values are:

$$A^T_{i,j} = A_{j,i}$$

In `numpy` the transpose is simply written `A.T`. There is also the function `np.transpose` which does the same.

### Exercise 4.4

- Create a random $4 \times 5$ matrix and verify that the above equality holds for it.
- What would be the outcome of $(A^T)^T$? Check this in `numpy`.

In [10]:
# 8<---------------------------------
A = np.random.normal(1, 0, (4,5))
for i in range(4):
    for j in range(5):
        print(A[i,j] == A.T[j,i])

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [11]:
# 8<--------------------------------
print(np.allclose(A.T.T, A))

True


## Inverse

- For scalar numbers the multiplicative inverse (aka reciprocal) of number $n$ is $\frac{1}{n}$, 
- Also written as $n^{-1}$. 
- This inverse has certain properties, like:
  - $n^{-1}n = 1$
  - $(n^{-1})^{-1} = n$

## Inverting matrices

- There is an analogous concept for matrices. 
- For a square matrix $A_{m \times m}$, its inverse is written $A^{-1}$ and it satisfies:

  - $A^{-1}A = I$ where $I$ is the $m \times m$ identity matrix
  - $(A^{-1})^{-1} = A$
  - $(A^T)^{-1} = (A^{-1})^T$

Not all matrices are invertible: a matrix needs to be square, and its [determinant](https://en.wikipedia.org/wiki/Determinant) needs to be non-zero. There is a function to invert matrices in `scipy.linalg` called `inv`.

In [12]:
from scipy.linalg import inv
A = np.random.uniform(0,1,(3,3))
print(A)
print(inv(A))

[[ 0.49097889  0.84919912  0.31654322]
 [ 0.79819363  0.20894901  0.00828292]
 [ 0.64928251  0.78287426  0.10600493]]
[[ 0.16443901  1.65638694 -0.62045962]
 [-0.83173504 -1.61109759  2.60954536]
 [ 5.13538909  1.75297276 -6.03832572]]


## Properties of matrix inverse
- $A^{-1}A = I$ where $I$ is the $m \times m$ identity matrix
- $(A^{-1})^{-1} = A$
- $(A^T)^{-1} = (A^{-1})^T$

### Exercise 4.5

Verify the three properties of the matrix inverse operations listed above for a random $m \times m$ numpy matrix. 

In [13]:
# 8<----------------------------------------------------------------
A = np.random.normal(0, 1, (5, 5))
print(np.allclose(  inv(A) @ A,   np.eye(5)         ))
print(np.allclose(  inv(inv(A)),  A                    ))
print(np.allclose(  inv(A.T),     inv(A).T             ))

True
True
True


In [14]:
# 8<----------------------------------------------
print(np.allclose( inv(A) @ A,  np.eye(5)))

True


## Ordinary Least Squares formula for Linear Regression

- Ready to implement the formula which can be used to find the coefficients of linear regression:

$$\hat\beta = (X^TX)^{-1}X^Ty$$

- Remember that $X$ has 
  - $N$ rows corresponding to the $N$ datapoints, and
  - $M$ columns corresponding to the $M$ predictors. 
  - The formula defines the vector $\hat\beta$ with the $M$ regression coefficients.

- We will apply this formula to the winequality dataset.


In [15]:
# Load winequality as a pandas dataframe
import pandas as pd
data = pd.read_csv("winequality-red.csv", delimiter=';')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [16]:
# Convert dataframe array into array of numeric values
Xy = data.values
print(Xy.shape)

(1599, 12)


In [17]:
# Extract features X and target y from Xy
X = Xy[:,:-1]
y = Xy[:,-1:]
print(X.shape)
print(y.shape)

(1599, 11)
(1599, 1)


In [18]:
# Add dummy constant feature
X_new = np.concatenate([ np.ones((1599,1)), X ], axis=1)
print(X_new)


[[  1.      7.4     0.7   ...,   3.51    0.56    9.4  ]
 [  1.      7.8     0.88  ...,   3.2     0.68    9.8  ]
 [  1.      7.8     0.76  ...,   3.26    0.65    9.8  ]
 ..., 
 [  1.      6.3     0.51  ...,   3.42    0.75   11.   ]
 [  1.      5.9     0.645 ...,   3.57    0.71   10.2  ]
 [  1.      6.      0.31  ...,   3.39    0.66   11.   ]]


### Exercise 4.6

Implement function `fit` which takes a matrix of predictors and a vector of targets, and returns the vector of regression coefficients computed according to the OLS formula.
Apply this function to the winequality data.

$$(X^T X)^{-1} X^T y$$

In [19]:
def fit(X, y):
    # 8<------------------------------------
    return inv(X.T @ X) @ X.T @ y

In [20]:
beta = fit(X_new, y)
print(beta)

[[  2.19652085e+01]
 [  2.49905527e-02]
 [ -1.08359026e+00]
 [ -1.82563948e-01]
 [  1.63312698e-02]
 [ -1.87422516e+00]
 [  4.36133331e-03]
 [ -3.26457970e-03]
 [ -1.78811638e+01]
 [ -4.13653144e-01]
 [  9.16334413e-01]
 [  2.76197699e-01]]


In [21]:
fit(X[:,:3], y)

array([[ 0.54531392],
       [ 1.93350958],
       [-0.2695241 ]])

### Exercise 4.7

Implement function `predict` which takes a vector of coefficients and a vector of predictors, and returns the predicted targets according to the regression formula (see beginning of notebook). Apply this function to the coefficients from the previous exercise, and the winequality data.

In [22]:
def predict(beta, X):
    # 8< --------------------------------
    return X @ beta


In [23]:
beta = fit(X_new, y)
y_pred = predict(beta, X_new)
print(np.concatenate([ y, y_pred], axis=1))

[[ 5.          5.03285045]
 [ 5.          5.13787974]
 [ 5.          5.20989474]
 ..., 
 [ 6.          5.94304254]
 [ 5.          5.47075621]
 [ 6.          6.00819633]]


### Exercise 4.8

Define the following two functions to quantify how well the regression is able to predict the targets:
- `mse` - mean squared error, defined as the mean of the squared difference between each prediction and true target: $$MSE(y, \hat{y}) = \frac{1}{N}\sum_{i=1}^N (y_i-\hat{y}_i)^2$$
- `mae` - mean absolute error, defined as the mean of the absolute difference between each prediction and true target: $$MAE(y, \hat{y}) = \frac{1}{N}\sum_{i=1}^N abs(y_i-\hat{y}_i)$$

Check how well your regression functions predict the targets in winequality according to these error measures.

In [24]:
def mse(y, y_pred):
    return np.mean((y - y_pred)**2)
def mse_silly(y, y_pred):
    return np.sum((y - y_pred)**2)/len(y)
def mae(y, y_pred):
    return np.mean(np.abs(y - y_pred))


In [25]:
print(mse(y, y_pred))
print(mse_silly(y, y_pred))

0.416767167221
0.416767167221


### Exercise 4.9

- Load the [iris.txt](iris.txt) data and extract the first three column into a predictor matrix, and the fourth column into a target vector. Apply the functions `fit` and `predict` to this data, and check the MSE and MAE of your predictions.

In [26]:
# 8<-------------------------
iris = pd.read_csv("iris.txt", delim_whitespace=True, header=None)
iris.head()

0    1    2    3       4
0  5.1  3.5  1.4  0.2  setosa
1  4.9  3.0  1.4  0.2  setosa
2  4.7  3.2  1.3  0.2  setosa
3  4.6  3.1  1.5  0.2  setosa
4  5.0  3.6  1.4  0.2  setosa

In [27]:
# extract first three columns
X = iris[[0,1,2]].values
# Add dummy bias column
X = np.concatenate([np.ones((150, 1)), X], axis=1)
# extract fourth column
y = iris[3].values
# Fit linear model
coef = fit(X, y)
y_pred = predict(coef, X)
print(mse(y, y_pred))
print(mae(y, y_pred))

0.0358686511382
0.143113459852
