# 5. Dense and sparse matrices

In this notebook in addition to NumPy we'll also be using SciPy. SciPy is a library for (mathematical) functions that are often used in scientific research.

## Scipy

- optimization, 
- interpolation, 
- integration, 
- linear algebra, 
- statistics 
- **sparse datastructures**

In [1]:
import numpy
import scipy
import scipy.sparse

## Dense versus sparse matrices


Sparseness can refer to:

- content
- representation

## Dense and sparse content

- A dense matrix is a matrix with a lot of nonzero elements.
- A sparse matrix is the opposite and contains of a lot of zeros. 

The sparsity/density can be computed by dividing the number of nonzero elements by the total number of elements.


## Sparse matrix representations

- For matrices with sparse content we can use sparse representations.
- A sparse representation is a represenation in which only the nonzero elements are stored, while the zeros are implicit. 
- Especially useful for large and sparse matrices.

## Advantages
The advantage of using a sparse matrix representation are:

- Memory: less memory is needed to store the matrix since the zero elements are not stored.
- Efficiency: for some operations zero elements can be skipped

## Examples

- Counting words in texts. A document-term matrix is created, which is a matrix where for every document a vector is representing the frequencies of the words that occur in that document. A document-term matrix tends to have a large proportion of zero elements.

- All diagonal matrices only have values on the diagonal and the other values are zeros, so these matrices can be better represented as a sparse matrix or alternatively as a vector of only the diagonal components.
- Upper or lower triangular matrix. Only approximately half of the records (including the diagonal) is non-zero and the other half is zeros. In the upper triangular matrix the upper part of the matrix has non-zero values and in the lower triangular matrix the lower part of the matrix has non-zero values. 

## Ways to store a sparse matrix

There are several different sparse matrix classes in SciPy:
- Dictionary of keys (dok_matrix)
- List of lists (lil_matrix)
- Coordinate list (coo_matrix)
- Diagonal storage (dia_matrix)
- Compressed sparse column (csc_matrix)
- Compressed sparse row (csr_matrix)
- Block sparse row matrix (bsr_matrix)


If you want to create a sparse matrix incrementally, it's best to use `dok` or `lil`.
You should then convert it to `csc` or `csr` for efficient matrix operations, such as matrix multiplication or inversion.

Below some different sparse matrix classes will be discussed separately.
For more information: http://docs.scipy.org/doc/scipy/reference/sparse.html

## Dictionary of keys (dok)

- Every key in the dictionary represents the row and column of the element
- Values in the dictionary represents the element at that particular position. 
- Elements with value 0 are not present in the dictionary, but they are assumed to be implicitly zero. 



In [2]:
# Create a dok matrix incrementally

S = scipy.sparse.dok_matrix((5, 5), dtype=numpy.int32)
for i in range(5):
    for j in range(5):
        S[i,j] = i - j
print(S)

  (1, 2)	-1
  (3, 2)	1
  (1, 3)	-2
  (3, 0)	3
  (2, 1)	1
  (2, 3)	-1
  (1, 4)	-3
  (4, 2)	2
  (1, 0)	1
  (0, 3)	-3
  (4, 0)	4
  (0, 1)	-1
  (3, 4)	-1
  (3, 1)	2
  (2, 4)	-2
  (2, 0)	2
  (4, 3)	1
  (0, 4)	-4
  (4, 1)	3
  (0, 2)	-2


### Exercise 5.1

In this exercise we will learn how to build a document-term matrix.
We'll build two functions.

- Create function `word_index`  which takes a list of words, and returns a dictionary mapping each unique word to an index. The role of this function is to associate word types with columns in the document-term matrix.

For example:
```python
word_index("A rose is a rose".split())
```
```
{'A': 0, 'a': 3, 'is': 2, 'rose': 1}
```
- Create function `word_count` which takes a list of texts (where text is a list of words), and returns two values:
   - the dictionary mapping words to indices (as computed by the function `word_index` above).
   - the `dok_matrix` which counts how many times each word occurs in each text. The matrix should be $M\times N$, where $M$ is the number of texts and  $N$ is the total number word types (i.e. total number of unique words). In your implementation you will use the function `word_index` to map words to indices.

Example:

```python
text = ['All human beings are born free and equal in dignity and rights'.split(),
       'They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood'.split()]
vocab, M = word_count(text)
print(M[0, vocab['and']])
print(M[1, vocab['reason']])
```       
Output:
```
2.0
1.0
```

In [3]:
# 8<------------------------------------------------
def word_index(words):
    D = {}
    i = 0
    for word in words:
        if word not in D:
            D[word] = i
            i += 1
    return D

strings = "A rose is a rose is a rose rose red rose".split()
#print(word_index(strings))
    
def word_count(texts):
    words = []
    for text in texts:
        for word in text:
            words.append(word)
    vocab = word_index(words)
    M = scipy.sparse.dok_matrix((len(texts), len(vocab)), dtype='int32')
    # fill the matrix
    for i in range(len(texts)):
        for word in texts[i]:
            j  = vocab[word]
            M[i, j] += 1
    return vocab, M
text = ['All human beings are born free and equal in dignity and rights'.split(),
       'They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood'.split()]
vocab, M = word_count(text)

print(M[0, vocab['and']])
print(M[1, vocab['reason']])

2
1


## Compressed sparse row (csr)

`scipy.sparse.csr_matrix(D, shape=(nrows, ncols), dtype=)`

- Advantages: efficient arithmetic operations, efficient row slicing and row operations, and fast matrix vector products. 

- Disadvantages: slow column slicing operations (use CSC for faster column slicing), and changes to the sparsity structure are expensive (use LIL or DOK instead). 


In [4]:
D = numpy.round(numpy.random.random((3,3)))
print(D)
S = scipy.sparse.csr_matrix(D, shape=(3,3), dtype=numpy.int32)
print(S)

[[ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]]
  (0, 2)	1
  (2, 0)	1


## Compressed sparse column (csc)

`scipy.sparse.csc_matrix(D, shape=(nrows, ncols), dtype=)`

- Advantages: efficient arithmetic operations, efficient column slicing, and fast matrix vector products (but CSR may be faster).

- Disadvantages: slow row slicing operations (use CSR instead), and changes tot he sparsity structure are expensive (use LIL or DOK). 


In [5]:
D = numpy.round(numpy.random.random((3,3)))
S = scipy.sparse.csc_matrix(D, shape=(3,3), dtype=numpy.int32)
print(S)

  (1, 0)	1
  (1, 1)	1
  (0, 2)	1


## Creating a sparse matrix

The following three letter abbreviations of the sparse representations are as format specifiers when creating sparse matrices: `dok, lil, coo, csr, csc, dia`, and `bsr`. 

Examples:
- Create the m by n identity matrix with the ones on the diagonal (k=0 is the main diagonal):  

`scipy.sparse.eye(m, n, k, dtype=, format= )`

- Create a m by n matrix with random elements (floats between 0 and 1) and specify the matrix density:

`scipy.sparse.rand(m, n, density=, format=, dtype= )`

In [6]:
# sparse identity matrix
E = scipy.sparse.eye(3, 4, 0, dtype=numpy.int32, format="dok" )
print(E.toarray())

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [7]:
# sparse random matrix
R = scipy.sparse.rand(5, 5, density=0.06, format="coo", dtype=numpy.float32)
print(R)

  (1, 2)	0.445076


## Checking for sparsity

- `scipy.sparse.issparse(x)`
- `scipy.sparse.isspmatrix(x)`
- `scipy.sparse.isspmatrix_dok(x), scipy.sparse.isspmatrix_lil(x), scipy.sparse.isspmatrix_coo(x)` etc.

All these functions return `True` in the case where the matrix is sparse and of the particular type and `False` otherwise.

In [8]:
R = scipy.sparse.rand(5,5,density=0.2, format="coo", dtype=numpy.float32)
print("Is sparse?", scipy.sparse.issparse(R))
print("Is Dictionary of Keys format?", scipy.sparse.isspmatrix_dok(R))
print("Is Coordinate lists format?", scipy.sparse.isspmatrix_coo(R) )

Is sparse? True
Is Dictionary of Keys format? False
Is Coordinate lists format? True


## Using the sparse representations

Sparse matrices can be used in the usual mathematical operations:

- addition, 
- substraction, 
- division, 
- multiplication

For elementwise multiplication, use: `x.multiply(y)`

http://docs.scipy.org/doc/scipy/reference/sparse.html

In [9]:
# mathematical transformations with sparse matrices
x = scipy.sparse.rand(3,3,density=0.5, format="csr", dtype=numpy.float32)
y = scipy.sparse.rand(3,3,density=0.5, format="csr", dtype=numpy.float32)
print("x=")
print(x)
print("y=")
print(y)
print("x+y=")
print(x+y)

x=
  (0, 1)	0.882563
  (0, 2)	0.118507
  (1, 0)	0.490286
  (1, 1)	0.944163
y=
  (0, 0)	0.130623
  (0, 1)	0.0538476
  (1, 0)	0.0802646
  (2, 0)	0.186728
x+y=
  (0, 0)	0.130623
  (0, 1)	0.936411
  (0, 2)	0.118507
  (1, 0)	0.570551
  (1, 1)	0.944163
  (2, 0)	0.186728


In [10]:
print("Matrix multiplication x y =")
print(x @ y)

print("CAUTION: x * y for sparse matrices means matrix multiplication, not elementwise")
print(x * y)
print("CAUTION: elementwise multiplication is done with `x.multiply(y)`:")
print(x.multiply(y))

Matrix multiplication x y =
  (0, 0)	0.0929672
  (1, 1)	0.0264007
  (1, 0)	0.139825
CAUTION: x * y for sparse matrices means matrix multiplication, not elementwise
  (0, 0)	0.0929672
  (1, 1)	0.0264007
  (1, 0)	0.139825
CAUTION: elementwise multiplication is done with `x.multiply(y)`:
  (0, 1)	0.0475239
  (1, 0)	0.0393526


## Common methods of sparse matrices

- `x.mean()`: the mean of the values in the matrix
- `x.minimum(y)`: elementwise minimum operation between matrix x and scalar y
- `x.transpose()` or `x.T`: return the transpose of the matrix as a sparse matrix.
- `x.toarray()`: convert sparse matrix into a regular numpy array
- `x.sum(axis=)`: calculate the sum over the matrix or the sum over one axis.
- `x.nonzero()`: return the indices of the non-zero elements.
- `x.reshape(shape)`: reshape the array to another shape.
- `x.multiply(y)`: pointwise multiplication of x with another matrix y.


In [11]:
print(x.minimum(1.0).toarray())

[[ 0.          0.88256329  0.11850704]
 [ 0.49028617  0.94416291  0.        ]
 [ 0.          0.          0.        ]]


In [12]:
# create a random 10 by 5 sparse matrix with density 0.4 in the dictionary of keys format 
x = scipy.sparse.rand(10,5,density=0.4, format="dok", dtype=numpy.float32)

# calculate the mean 
print("Mean over the total matrix: ", x.mean())
print("Mean for every column: ", x.mean(axis=0))

# calculate the sum over the matrix
print("Total sum of the matrix:", x.sum())

Mean over the total matrix:  0.197325
Mean for every column:  [[ 0.06939099  0.29333231  0.17233849  0.28117812  0.170384  ]]
Total sum of the matrix: 9.86624


In [13]:
# create sparse matrix
x = scipy.sparse.rand(10,5,density=0.4, format="dok", dtype=numpy.float32)

# transpose
print("Transpose: ", x.transpose())

# multiply pointwise
y = scipy.sparse.rand(10, 5,density=0.2, format="dok", dtype=numpy.float32)
print("Multiply pointwise: ", x.multiply(y))



Transpose:    (1, 2)	0.984691
  (0, 1)	0.312098
  (3, 2)	0.763496
  (1, 3)	0.320638
  (3, 3)	0.186698
  (4, 5)	0.497746
  (3, 1)	0.110987
  (2, 7)	0.0822834
  (1, 6)	0.929128
  (1, 1)	0.894664
  (1, 5)	0.526821
  (2, 6)	0.567176
  (2, 3)	0.710295
  (2, 1)	0.489033
  (4, 3)	0.466433
  (3, 7)	0.194091
  (4, 2)	0.956573
  (0, 3)	0.293916
  (0, 8)	0.458673
  (0, 2)	0.0344961
Multiply pointwise:    (1, 1)	0.874292
  (3, 4)	0.132822
  (5, 4)	0.0742887
  (6, 2)	0.0431959


## Important warnings

### Mean subtraction

When subtracting the mean from all values of a sparse matrix the sparseness of the matrix is destroyed. 

Subtracting the mean will lead to a matrix with almost no zero values and all the old zero values will now have the value -mean. 

The same warning hold for normalization or standardization of the matrix.

Note that, inconsistently, the addition of a scalar to a sparse matrix does not give an error.

In [14]:
# the result of mean substraction of a sparse matrix is a dense matrix
x = scipy.sparse.rand(10,5,density=0.4, format="dok", dtype=numpy.float32)
print("mean: ", x.mean())
print(x - x.mean())


mean:  0.19556


NotImplementedError: subtracting a nonzero scalar from a sparse matrix is not supported

### Dot product between sparse matrices
When using sparse matrices you should not use the `numpy.dot` function, as this function does not understand sparse matrices.

Use `x.dot(y)` or `x @ y` instead.

Reference: http://docs.scipy.org/doc/scipy/reference/sparse.html#matrix-vector-product


In [15]:
# dot product 
x = scipy.sparse.dok_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
y = numpy.array([5, 6, 0])
print(x.toarray())
print(y)

print(x.dot(y))

[[1 2 0]
 [0 0 3]
 [4 0 5]]
[5 6 0]
[17  0 20]


In [16]:
print(x @ y)

[17  0 20]


In [17]:
# DO NOT DO THIS
print(numpy.dot(x, y))

[ <3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Dictionary Of Keys format>
 <3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Dictionary Of Keys format>
 <3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Dictionary Of Keys format>]


## Missing operations

Certain operations are not available for sparse matrices: 
- either because they are not compatible with sparsity, 
- or they simply haven't been implemented. 

So you may find that you occasionaly need to convert a sparse matrix to a numpy array (using `.toarray()`) to perform an operation. 

Be careful when doing this with very large matrices: they will most likely not fit in memory, and crash your Python session.

Some commonly used missing functions include:

- `.argmax`
- `.argmin`
- `.argsort`

### Exercise 5.2

Given a word index dictionary and a document-term matrix returned by `word_count`, find the most frequent word for each row.

In [18]:
# 8<--------------------------------------------
documents = ['a a a b b c'.split(),
            'c foo foo bar'.split(),
             'bar bar one two'.split()]
vocab, M = word_count(documents)
print(M.toarray())

def most_frequent(V, M):
    # Find column indices of most common words
    f = M.toarray().argmax(axis=1)
    # create mapping from column indices to words
    V_inv = dict((v, k) for k,v in V.items())
    # for each document return the commonest word    
    return [ (docid, V_inv[colid]) for docid, colid in enumerate(f) ]

print(most_frequent(vocab, M))

[[3 2 1 0 0 0 0]
 [0 0 1 2 1 0 0]
 [0 0 0 0 2 1 1]]
[(0, 'a'), (1, 'foo'), (2, 'bar')]


In [19]:
print(list(enumerate("a b c".split())))

[(0, 'a'), (1, 'b'), (2, 'c')]


### Exercise 5.3

Function `f` takes a document-term matrix, and returns another matrix. Analyze the code in `f` and try to figure out what this function is doing and how to interpret the result it returns.
```python
def f(D):
    M = D.minimum(1.0)
    return M.dot(M.T)
```

In [20]:
def f(D):
    "Works on sparse matrices"
    M = D.minimum(1.0)
    return M.dot(M.T)

def g(D):
    "Works on arrays"
    M = numpy.minimum(D, 1.0)
    return M.dot(M.T)

M = M[:3,:5]
 

In [21]:
print(f(M).toarray())
print(g(M.toarray()))

[[ 3.  1.  0.]
 [ 1.  3.  1.]
 [ 0.  1.  1.]]
[[ 3.  1.  0.]
 [ 1.  3.  1.]
 [ 0.  1.  1.]]


### Exercise 5.4

- Create a list of texts by reading the first 1000 lines from [coco_val.txt](coco_val.txt). Create matrix A with the document-term matrix from these 1000 sentences. Create another matrix B by converting the matrix A from `dok` format to `csr` format. Use the ipython command `%timeit` to compare whether it's faster to apply function `f` (see above) to matrix A or B.
- Create matrix C by converting A to a regular numpy array. Write function `g` which is like `f`, but works on regular numpy array arrays. Use `%timeit` to see how fast g is when applied to matrix C.

In [22]:
# 8<---------------------------
lines = [ line.split() for line in open("coco_val.txt")][:1000]

In [23]:
# 8<----------------------------
vocab, A = word_count(lines)
B = A.tocsr()
C = A.toarray()
print(A.shape)
print(B.shape)
print(C.shape)

(1000, 1404)
(1000, 1404)
(1000, 1404)


In [24]:
# 8<----------------------------
%timeit f(A)

30.6 ms ± 321 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
# 8<----------------------------
%timeit f(B)

25.5 ms ± 2.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
# 8<----------------------------
%timeit g(C)

356 ms ± 114 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Exercise 5.5

There are a number of ways of measuring similarity between documents. For this exercise we'll try to use the number of unique words the documents have in common (word overlap).


1. Define function `similarity` which takes a document-term matrix, and returns the matrix where the value in the row $i$ and column $j$ is the word overlap between the $i$th and $j$th document.
3. Calculate the overlap similarity matrix for sentences in [coco_val.txt](coco_val.txt). For the first 20 sentences, display the 3 most similar sentences according to this matrix.
4. Word overlap is a very simplistic similarity measure. Suggest, and possibly implement, a better way of measuring similarity between documents based on a document-term matrix.

In [27]:
# 8<----------------------------
def similarity(D):
    "Computes word overlap between pairs of documents in document-term matrix D"
    M = D.minimum(1.0)
    return M @ M.T

In [28]:
# 8<----------------------------
lines = [ line.split() for line in open("coco_val.txt")][:5000]

In [29]:
# 8<----------------------------
vocab, M = word_count(lines)

In [30]:
# 8<----------------------------
S = similarity(M)

In [31]:
# 8<----------------------------
for i in range(20):
    print(" ".join(lines[i]))
    # convert row to array
    row = S[i, :].toarray()[0, :]
    # look for 3 highest values
    for j in row.argsort()[-4:-1]:
        print(S[i, j], " ".join(lines[j]))
    print()

a child holding a flowered umbrella and petting a yak
4.0 a small child holding a kite and eating a treat
4.0 a woman walking with a man and holding an umbrella looks off to the side
4.0 an adult standing holding surfboard and a child kneeling by water

a young man holding an umbrella next to a herd of cattle
6.0 a woman holding an umbrella standing next to a black wall
7.0 the silhouette of a man under an umbrella sitting next to the water
7.0 a black and white photo of a man sitting by the water holding an umbrella to give him shade

a young boy barefoot holding an umbrella touching the horn of a cow
6.0 a black and white photo of a man sitting by the water holding an umbrella to give him shade
6.0 a young man holding an umbrella next to a herd of cattle
10.0 a young boy with an umbrella who is touching the horn of a cow

a young boy with an umbrella who is touching the horn of a cow
6.0 a young man is skateboarding in the middle of the street with cars passing in both directions
6.0