# 6. Distance and similarity metrics

In [1]:
import numpy as np

## Distance metrics

- Distance metric measures the distance between two points $x$ and $y$. 
- A point in $n$-dimensional space can be represented by a vector of length $n$. 

## Applications

- k-nearest neighbors algorithm: to calculate the k points that are closest to the new unlabelled point.
- Clustering algorithms: to calculate the distance between records inside the cluster and to calculate the distance between different clusters. For example, k-means clustering.

## Examples
Some frequently used distance metrics include:
- Euclidean distance: $$D_{euc}(x, y) = \left(\sum_{i=1}^{n}(x_{i}-y_{i})^2\right)^{0.5}$$
- Manhattan distance: $$D_{manh}(x, y) = \sum_{i=1}^{n} abs(x_{i}-y_{i})$$

## Properties
In general, distance metrics satisfy some properties such as:
- The distance between two points is non-negative. 
- The distance from a point to the point itself is equal to 0. 
- The distance from point $i$ to point $j$ is exactly equal to the distance from point $j$ to point $i$ (symmetry). 
- The distance from point $i$ to point $j$ via point $k$ is always longer or equal than the direct distance from $i$ to $j$ (triangle inequality). 

In [2]:
# function to calculate manhattan distance between two points x and y
def manhattan_distance(x, y):
    return np.sum(np.abs(x-y))
        
x = np.array([1,3])
y = np.array([2,4])
print("Manhattan distance: ", manhattan_distance(x, y))

Manhattan distance:  2


### Exercise 6.1

Create a function to calculate the Euclidean distance between two points x and y. 
Do not use explicit loops.

For example:
```python
a = np.array([0.0, 0.0])
b = np.array([1.0, 1.0])
c = np.array([2.0, 2.0])
print(euclidean(a, b))
print(euclidean(a, c))
```
Output:
```
1.41421356237
2.82842712475
```

In [3]:
# 8<....................................................
def euclidean(a, b):
    return ((a-b)**2).sum()**0.5

a = np.array([0.0, 0.0])
b = np.array([1.0, 1.0])
c = np.array([2.0, 2.0])
print(euclidean(a, b))
print(euclidean(a, c))

1.41421356237
2.82842712475


### Exercise 6.2

Load the iris data into a 150x4 numpy array. Compute the Euclidean distance between the first row and each other row. Print the row with the minimum distance to the first row.

In [4]:
# 8<.........................
import pandas as pd
iris = pd.read_csv("iris.txt", delim_whitespace=True, header=None)
data = iris[[0,1,2,3]].values
print(data.shape)


(150, 4)


In [5]:
distances = np.array([ euclidean(data[0], data[i]) for i in range(0, data.shape[0])])
print("Minimum distance:", distances[1:].min())

j = distances[1:].argmin()
print("Index of row with minimum distance", j)
print("Row 0 and row with minimum distance:")
print(data[0])
print(data[j])

Minimum distance: 0.1
Index of row with minimum distance 16
Row 0 and row with minimum distance:
[ 5.1  3.5  1.4  0.2]
[ 5.4  3.9  1.3  0.4]


## Similarity

- A similarity metric quantifies how similar two objects are. 
- Often used interchangebly with distance metrics

## Cosine similarity
- When the cosine is equal to 1 the vectors point in the same direction, and when the cosine is equal to -1 then the vectors are the opposite of each other.
- Cosine similarity: $$cosine(x, y) = \frac{x^Ty}{||x||\cdot ||y||} = \frac{\sum_{i=1}^n x_i y_i}{\left(\sum_{i=1}^n x_{i}^2\right)^{0.5} \left(\sum_{i=1}^n y_{i}^2\right)^{0.5}}$$

- The cosine similarity between $x$ and $y$ is the dot product between $x$ and $y$ divided by the product of the L2-norms of $x$ and $y$.

## Applications of cosine similarity

- In text-mining the cosine similarity can be used to represent the similarity between two documents. We can represent documents as vectors of word counts or similar weights.

- High cosine similarity between two such vectors can be interpreted as these two documents sharing many words in common.

### Exercise 6.3
Create a function that calculates the cosine similarity between two vectors. Do not use for-loops.

For example:
```python
a = np.array([0.0, 1.0])
b = np.array([1.0, 0.0])
c = np.array([0.0, -1.0])
print(cosine(a, b))
print(cosine(a, a))
print(cosine(a, c))
```
Output:
```
0.0
1.0
-1.0
```


In [6]:
# 8<...........................................
def cosine1(a, b):
    "Definition of cosine using the dot product operator"
    return a @ b / ((a @ a) **0.5 * (b @ b) **0.5)

def cosine2(a, b):
    "Definition of cosine using elementwise multiplication and summation"
    return (a*b).sum()/((a**2).sum()**0.5 * (b**2).sum()**0.5)

a = np.array([0.0, 1.0])
b = np.array([1.0, 0.0])
c = np.array([0.0, -1.0])

print(cosine1(a, b))
print(cosine2(a, b))

print(cosine1(a, a))
print(cosine2(a, a))

print(cosine1(a, c))
print(cosine2(a, c))

0.0
0.0
1.0
1.0
-1.0
-1.0


## Distance measures for comparing strings

Distance measures for comparing strings with each other:
- Hamming distance: number of positions at which two strings of the same length differ.
    $$D_{hamming}(x, y) =  \sum_{i=1}^{n} x_{i} \neq y_{i} $$
- Levenshtein distance: the minimum number of operations required to transform one string into another string. The operations are insertion, deletion and substitutions and each operations has a cost (often unit costs are used). The Levenshtein distance is commonly used when similarity between two words needs to be measured. 

### Exercise 6.3
Create a function to calculate the Hamming distance between two strings. The strings need to have the same length.

For example:

```python
a = 'Panama'
b = 'Pamela'
hamming(a, b)
```
Output:
```
3
```

In [7]:
# 8< .....................................
def hamming1(a, b):
    "Definition of Hamming distance which checks for length, implemented with a loop."
    if len(a) != len(b):
        raise ValueError("Unqual string lengths")
    return sum((a[i] != b[i] for i in range(len(a))))


def hamming2(a, b):
    "Definition of Hamming distance which uses numpy vectorized operations."
    a = np.array(list(a))
    b = np.array(list(b))
    return (a != b).sum()
               
a = 'Panama'
b = 'Pamela'
print(hamming1(a, b))
print(hamming2(a, b))

3
3


In [8]:
# 8<--------------------------------
a = 'Panama'
b = 'Pamelaxxx'
print(hamming1(a, b))

ValueError: Unqual string lengths

In [9]:
# 8<--------------------------------
print(hamming2(a, b))

ValueError: shape mismatch: objects cannot be broadcast to a single shape

## Distance metrics in scikit-learn

- [Scikit-learn](http://scikit-learn.org/stable/) is a library for machine learning algorithms in Python. Scikit-learn includes functions for classification, regression, clustering, dimensionality reduction, model selection and preprocessing. 

- The class to calculate distances is [sklearn.neighbors.DistanceMetric](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html)

- The ``DistanceMetric`` class includes different distance metrics, such as Euclidean and Manhattan, Chebyshev, Minkowski, Mahalanobis, Hamming etc.

- The most important methods of the ``DistanceMetric`` class are the ``get_metric`` and the ``pairwise`` functions. 

- The ``get_metric`` function is used to specify which metric is used, for example 'euclidean' or 'manhattan'. 
- The ``pairwise`` function is used to calculate the pairwise distances between points in an array x. 
- There is also a simple function to calculate pairwise distances according to a number of metrics:
```python
from sklearn.metrics.pairwise import pairwise_distances
```


In [10]:
import sklearn.neighbors
from sklearn.metrics.pairwise import pairwise_distances

# we want to calculate the pairwise distance between three points in a 2D space
x = np.array([[1,3], [2, 4], [1, 6]])

# Euclidean distance
d1 = sklearn.neighbors.DistanceMetric.get_metric('euclidean')
print("Euclidean distance:")
print(d1.pairwise(x))
print(pairwise_distances(x, metric='euclidean'))

Euclidean distance:
[[ 0.          1.41421356  3.        ]
 [ 1.41421356  0.          2.23606798]
 [ 3.          2.23606798  0.        ]]
[[ 0.          1.41421356  3.        ]
 [ 1.41421356  0.          2.23606798]
 [ 3.          2.23606798  0.        ]]


In [11]:
# Manhattan distance
d2 = sklearn.neighbors.DistanceMetric.get_metric('manhattan')
print("Manhattan distance:")
print(d2.pairwise(x))
print(pairwise_distances(x, metric='manhattan'))

Manhattan distance:
[[ 0.  2.  3.]
 [ 2.  0.  3.]
 [ 3.  3.  0.]]
[[ 0.  2.  3.]
 [ 2.  0.  3.]
 [ 3.  3.  0.]]


## Cosine similarity in scipy and scikit-learn

- Cosine similarity is implemented in both `scipy` and in `scikit-learn`.

- In scipy:
`scipy.spatial.distance.cosine(x,y)` calculates the cosine distance between two points `x` and `y` where `x` and `y` are both represented by a vector.

- Note that in order to convert the distance to similarity, you should subtract distance from 1.

- In scikit-learn:
`sklearn.metrics.pairwise.cosine_similarity(x)` calculates the pairwise cosine similarities between all rows in array `x`.


**IMPORTANT** Verify, and remember, which of these implementations work with sparse matrices. 

In [12]:
# cosine similarity in scipy 

import scipy.spatial.distance
x = np.array([1, 0, -1])
y = np.array([-1,-1, 0])
print(1 - scipy.spatial.distance.cosine(x, y))

-0.5


In [13]:
# pairwise cosine similarity in sklearn
import sklearn.metrics.pairwise
x = np.array([[1, 0, -1], [-1,-1, 0]])
print(sklearn.metrics.pairwise.cosine_similarity(x))

[[ 1.  -0.5]
 [-0.5  1. ]]


In [14]:
X = scipy.sparse.csr_matrix([[1, 0, -1], [-1,-1, 0]])
print(1 - scipy.spatial.distance.cosine(X[0,:], X[1,:]))

ValueError: dimension mismatch

In [15]:
print(sklearn.metrics.pairwise.cosine_similarity(X))

[[ 1.  -0.5]
 [-0.5  1. ]]


### Exercise 6.4 

Use the function `word_count` which you implemented in notebook [5_sparse.ipynb](5_sparse.ipynb) to create a document-term matrix from the first 100 rows of file [coco_val.txt](coco_val.txt). 
- Does your cosine function work on rows of the sparse document-term matrix? If not, do you know why not?
- Compute the pairwise cosine similarity between the rows of your document-term matrix using the `sklearn` implementation. Which document is the most similar to the first row according to cosine similarity?  
- Based on the above experiment, suggest ways of modifying the word counts to make the cosine similarity more useful as a metric of text similarity. Implement your idea and test it.

In [16]:
from wc import word_count
texts = [ line.split()  for line in open("coco_val.txt")][:100]
vocab, M = word_count(texts)

In [17]:
# 8<-----------------------
# Does your cosine function work on rows of the sparse document-term matrix? If not, do you know why not?
print(cosine2(M[0,:], M[1,:]))

ValueError: dimension mismatch

In [18]:
# 8<-----------------------
# Compute the pairwise cosine similarity between the rows of your document-term matrix using the sklearn implementation. 
# Which document is the most similar to the first row according to cosine similarity? 
print("Most similar sentence to texts[0] according to cosine similarity")
S = sklearn.metrics.pairwise.cosine_similarity(M)
j = S[0,:].argsort()[-2]
print(texts[0])
print(texts[j])

Most similar sentence to texts[0] according to cosine similarity
['a', 'child', 'holding', 'a', 'flowered', 'umbrella', 'and', 'petting', 'a', 'yak']
['a', 'woman', 'on', 'a', 'motorcycle', 'wearing', 'a', 'bag', 'and', 'passing', 'a', 'car']


In [19]:
# 8<-----------------------
# Based on the above experiment, suggest ways of modifying the word counts to make the cosine similarity more useful as a metric of text similarity. 
# Implement your idea and test it.
print("Most similar sentence to texts[0] according to cosine similarity (remove stopwords)")
stopwords = ['a', 'and', 'the', 'is', 'in', 'on', 'at']
texts = [ [ word for word in text if word not in stopwords] for text in texts ]
vocab, M = word_count(texts)
S = sklearn.metrics.pairwise.cosine_similarity(M)
j = S[0,:].argsort()[-2]
print(texts[0])
print(texts[j])

Most similar sentence to texts[0] according to cosine similarity (remove stopwords)
['child', 'holding', 'flowered', 'umbrella', 'petting', 'yak']
['boy', 'holding', 'an', 'umbrella', 'while', 'standing', 'next', 'to', 'livestock']


### Exercise 6.5

Scikit learn has a couple of classes which are useful for creating various versions of document-word matrices:
- `sklearn.feature_extraction.text.CountVectorizer`
- `sklearn.feature_extraction.text.TfidfVectorizer`

Read the documentation of these classes and try to apply them on the [coco_val.txt](coco_val.tx) data. 
- Compute similarities/distances using a few versions of these document-word matrices and check how they compare to using plain word-counts as we have been doing so far. 

In [20]:
# 8<-----------------------
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

doc = [ line.strip() for line in open('coco_val.txt')]

print("Word counts with CountVectorizer")
cv = CountVectorizer(analyzer='word', lowercase=False, tokenizer=lambda x: x.split())
M1 = cv.fit_transform(doc)
print("Number of features: ", len(cv.get_feature_names()))

print("Character n-grams with CountVectorizer")
cvng = CountVectorizer(analyzer='char', ngram_range=(1,5), lowercase=False)
M2 = cvng.fit_transform(doc)
print("Number of features: ", len(cvng.get_feature_names()))

print("Similarities according to M1 vs M2")
print(doc[0])
r11 = M1[0].toarray()
r21 = M2[0].toarray()
for i in range(1, 20):
    r12 = M1[i].toarray()    
    r22 = M2[i].toarray()
    print("{:.3} {:.3} {}".format(cosine2(r11, r12), cosine2(r21, r22), doc[i]))
    

Word counts with CountVectorizer
Number of features:  7213
Character n-grams with CountVectorizer
Number of features:  75257
Similarities according to M1 vs M2
a child holding a flowered umbrella and petting a yak
0.535 0.689 a young man holding an umbrella next to a herd of cattle
0.516 0.652 a young boy barefoot holding an umbrella touching the horn of a cow
0.438 0.585 a young boy with an umbrella who is touching the horn of a cow
0.395 0.661 a boy holding an umbrella while standing next to livestock
0.333 0.538 a narrow kitchen filled with appliances and cooking utensils
0.316 0.501 a galley kitchen with cabinets and appliances on both sides
0.452 0.532 a hallway leading into a white kitchen with appliances
0.468 0.517 doorway view of a kitchen with a sink stove refrigerator and pantry
0.0 0.424 the pantry door of the small kitchen is closed
0.606 0.597 a little girl holding a kitten next to a blue fence
0.438 0.602 girl in a tank top holding a kitten in her back yard
0.553 0.604 a