# Question 1

In [1]:
import numpy as np

In [4]:
def transformRandomBetaValues(a, b, number):
    z = np.random.uniform(a, b, number)
    return (np.sin(z))**4

In [5]:
np.random.seed(1)

transformRandomBetaValues(10.1,10,12)

array([0.12281276, 0.1035537 , 0.15264817, 0.13063077, 0.14170836,
       0.14571159, 0.13884394, 0.12764938, 0.12417199, 0.11483297,
       0.12266751, 0.10567827])

# Question 2

In [6]:
import numpy as np

In [14]:
def subsampleMedianDiff(a, x, y):
    return np.median(a),np.median(a)


In [15]:
a = np.array([4,5,7,8,2,3,9,11,10])

subsampleMedianDiff(a,2,3)

(7.0, 7.0)

In [12]:
a = np.array([4,5,7,8,2,3,9,11,10])

print(a[np.where(a) > 3])

TypeError: '>' not supported between instances of 'tuple' and 'int'

# Question 3

In [16]:
import numpy as np

In [44]:
def matrixCutter(a):
    b = a.reshape(int(a.size**0.5), int(a.size**0.5))
    return b[0:2,0:b.shape[0] - 1]

In [49]:
np.random.seed(3)

a = np.random.randint(0, 100, 100)
x = np.linspace(1,100,100)

print(matrixCutter(a))
print(matrixCutter(x))

[[24  3 56 72  0 21 19 74 41]
 [21 38 96 20 44 93 39 14 26]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19.]]


# Question 4

In [50]:
import numpy as np

In [66]:
def removeLastTwoEntries(a):
    return a[0:a.shape[0]-2,0:a.shape[1]-2,0:a.shape[2]-2]

In [68]:
#test case 1
a = np.arange(1,121).reshape((4,5,6))
print("Matric A:")
print(a)
print()

b = removeLastTwoEntries(a)

print("Matric B:")
print(b)
print()

print("Shapes:")
print(a.shape, b.shape)

Matric A:
[[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]]

 [[ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]

Matric B:
[[[ 1  2  3  4]
  [ 7  8  9 10]
  [13 14 15 16]]

 [[31 32 33 34]
  [37 38 39 40]
  [43 44 45 46]]]

Shapes:
(4, 5, 6) (2, 3, 4)


In [71]:
#test case 2
np.random.seed(3)
a = np.random.randint(-10, 10, 125).reshape((5,5,5))
print("Matric A:")
print(a)
print()

b = removeLastTwoEntries(a)

print("Matric B:")
print(b)
print()

print("Shapes:")
print(a.shape, b.shape)


Matric A:
[[[  0  -7  -2 -10   9]
  [  0   1  -1   0  -4]
  [-10   2  -3   4   7]
  [ -8  -8  -9   9  -5]
  [ -2   4  -9   0  -3]]

 [[  1  -9   5   6  -5]
  [  7   4 -10 -10  -1]
  [  8  -5  -3  -5   4]
  [ -9   7  -9   0   1]
  [ -6  -7   6   6 -10]]

 [[  6   8   8   1 -10]
  [  3  -5   6  -9   7]
  [  8  -8  -6  -2   2]
  [  6   0   6  -6   7]
  [  7  -2  -3 -10   6]]

 [[ -1  -9   5   1   0]
  [  6   6   2  -6   2]
  [  2   9   6  -8  -3]
  [  8  -9  -7   3   8]
  [ -9   8  -8  -7   7]]

 [[  1  -3  -9   1 -10]
  [  6   1  -2  -2   4]
  [  2   9  -6  -1   8]
  [ -5  -1   0   7  -1]
  [-10   3   2  -3  -6]]]

Matric B:
[[[  0  -7  -2]
  [  0   1  -1]
  [-10   2  -3]]

 [[  1  -9   5]
  [  7   4 -10]
  [  8  -5  -3]]

 [[  6   8   8]
  [  3  -5   6]
  [  8  -8  -6]]]

Shapes:
(5, 5, 5) (3, 3, 3)
