# Question 1

In [1]:
import numpy as np

In [4]:
def transformRandomBetaValues(a, b, number):
    z = np.random.uniform(a, b, number)
    return (np.sin(z))**4

In [5]:
np.random.seed(1)

transformRandomBetaValues(10.1,10,12)

array([0.12281276, 0.1035537 , 0.15264817, 0.13063077, 0.14170836,
       0.14571159, 0.13884394, 0.12764938, 0.12417199, 0.11483297,
       0.12266751, 0.10567827])

# Question 2

In [6]:
import numpy as np

In [14]:
def subsampleMedianDiff(a, x, y):
    return np.median(a),np.median(a)


In [15]:
a = np.array([4,5,7,8,2,3,9,11,10])

subsampleMedianDiff(a,2,3)

(7.0, 7.0)

In [12]:
a = np.array([4,5,7,8,2,3,9,11,10])

print(a[np.where(a) > 3])

TypeError: '>' not supported between instances of 'tuple' and 'int'

# Question 3

In [16]:
import numpy as np

In [44]:
def matrixCutter(a):
    b = a.reshape(int(a.size**0.5), int(a.size**0.5))
    return b[0:2,0:b.shape[0] - 1]

In [49]:
np.random.seed(3)

a = np.random.randint(0, 100, 100)
x = np.linspace(1,100,100)

print(matrixCutter(a))
print(matrixCutter(x))

[[24  3 56 72  0 21 19 74 41]
 [21 38 96 20 44 93 39 14 26]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19.]]
